// _frontend_vue/src/components/LoginComponent.vue
<template>
  <div>
    <h2>Login</h2>
    <form @submit.prevent="handleLogin">
      <div>
        <label for="username">Email:</label>
        <input type="email" id="username" v-model="username" required />
      </div>
      <div>
        <label for="password">Password:</label>
        <input type="password" id="password" v-model="password" required />
      </div>
      <button type="submit">Login</button>
    </form>
    <div v-if="loading">Logging in...</div>
    <div v-if="error">{{ error }}</div>
    <div v-if="tokens">
      <p>Login successful!</p>
      <p>ID Token: {{ tokens.id_token }}</p>
      <p>Access Token: {{ tokens.access_token }}</p>
      <p>Refresh Token: {{ tokens.refresh_token }}</p>
    </div>
  </div>
</template>

<script>
  import axios from 'axios';
  import { useRouter } from 'vue-router';
  import auth from '../store/auth';

  export default {
    data() {
      return {
        username: '',
        password: '',
        loading: false,
        error: null,
        tokens: null,
      };
    },
    setup() {
      const router = useRouter();
      return { router };
    },
    methods: {
      async handleLogin() {
        this.loading = true;
        this.error = null;
        this.tokens = null;

        try {
          const response = await axios.post('https://fv0qkf13r5.execute-api.us-east-1.amazonaws.com/dev-cors', {
            username: this.username,
            password: this.password,
          });

          this.tokens = JSON.parse(response.data.body);

          // Set authentication state
          auth.login();

          // Redirect to the ImageGenerator component
          this.router.push('/generate');
        } catch (error) {
          this.error = error.response?.data?.error || 'An error occurred';
        } finally {
          this.loading = false;
        }
      },
    },
  };
</script>

<style scoped>
  form {
    display: flex;
    flex-direction: column;
    max-width: 400px;
    margin: auto;
  }

  div {
    margin-bottom: 1em;
  }

  label {
    margin-bottom: 0.5em;
    color: #333;
  }

  input {
    border: 1px solid #ccc;
    padding: 0.5em;
    font-size: 1em;
  }

  button {
    padding: 0.7em;
    background-color: #007bff;
    color: white;
    border: none;
    font-size: 1em;
    cursor: pointer;
  }

  button:hover {
    background-color: #0056b3;
  }
</style>

// frontend/src/components/LoginComponent.jsx
import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../AuthContext';
import './LoginComponent.css';

const LoginComponent = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [email, setEmail] = useState(''); // For sign-up
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [isLogin, setIsLogin] = useState(true); // State to switch between login and signup
  const navigate = useNavigate();
  const { login } = useAuth();

  const handleLogin = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    const input = {
      username: username,
      password: password,
      action: "/login"
    };

    const params = {
      input: JSON.stringify(input),
      stateMachineArn: 'arn:aws:states:us-east-1:761577439658:stateMachine:authentication'
    };

    try {
      const response = await axios.post('https://xckp6yia6e.execute-api.us-east-1.amazonaws.com/dev/login', params, {
        headers: {
          'Content-Type': 'application/json'
        }
      });

      console.log("Response", response);
      login();
      navigate('/generate');
    } catch (error) {
      console.log("ERROR", error);
      console.log("ERROR RESPONSE", error.response);
      const errorMessage = error.response?.data?.message || 'An error occurred';
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleSignup = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    const input = {
      username: username,
      email: email,
      password: password,
      action: "/signup"
    };

    const params = {
      input: JSON.stringify(input),
      stateMachineArn: 'arn:aws:states:us-east-1:761577439658:stateMachine:authentication'
    };

    try {
      const response = await axios.post('https://xckp6yia6e.execute-api.us-east-1.amazonaws.com/dev/signup', params, {
        headers: {
          'Content-Type': 'application/json'
        }
      });

      console.log("Response", response);
      // Handle post-signup logic (e.g., redirect to verification page)
    } catch (error) {
      console.log("ERROR", error);
      console.log("ERROR RESPONSE", error.response);
      const errorMessage = error.response?.data?.message || 'An error occurred';
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-container">
      <div className="login-box">
        <div className="tabs">
          <button className={`tab ${isLogin ? 'active' : ''}`} onClick={() => setIsLogin(true)}>Login</button>
          <button className={`tab ${!isLogin ? 'active' : ''}`} onClick={() => setIsLogin(false)}>Sign Up</button>
        </div>
        {isLogin ? (
          <div>
            <h2 className="login-title">Login</h2>
            <form onSubmit={handleLogin} className="login-form">
              <div className="form-group">
                <label htmlFor="username">Email:</label>
                <input
                  type="email"
                  id="username"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                />
              </div>
              <div className="form-group">
                <label htmlFor="password">Password:</label>
                <input
                  type="password"
                  id="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <button type="submit" className="login-button">Login</button>
            </form>
            {loading && <div className="loading">Logging in...</div>}
            {error && <div className="error">{error}</div>}
          </div>
        ) : (
          <div>
            <h2 className="login-title">Sign Up</h2>
            <form onSubmit={handleSignup} className="login-form">
              <div className="form-group">
                <label htmlFor="username">Username:</label>
                <input
                  type="text"
                  id="username"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  required
                />
              </div>
              <div className="form-group">
                <label htmlFor="email">Email:</label>
                <input
                  type="email"
                  id="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                />
              </div>
              <div className="form-group">
                <label htmlFor="password">Password:</label>
                <input
                  type="password"
                  id="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <button type="submit" className="login-button">Sign Up</button>
            </form>
            {loading && <div className="loading">Signing up...</div>}
            {error && <div className="error">{error}</div>}
          </div>
        )}
      </div>
    </div>
  );
};

export default LoginComponent;
