// frontend/src/components/ImageGallery.jsx
import React, { useState } from 'react';
import axios from 'axios';
import './ImageGallery.css';

const ImageGallery = () => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [imageUrls, setImageUrls] = useState([]);

  const fetchImages = async () => {
    setLoading(true);
    setError(null);
    setImageUrls([]);

    const params = {
      bucket: 'ca-store-images',
      prefix: 'generated-images/',
    };

    const input = {
      params: params,
      action: "/fetchAll"
    };

    const apiParams = {
      input: JSON.stringify(input),
      stateMachineArn: 'arn:aws:states:us-east-1:761577439658:stateMachine:imageHandler'
    };

    try {
      const response = await axios.get('https://00ewcs17p7.execute-api.us-east-1.amazonaws.com/fetchAll', params, {
        headers: {
          'Content-Type': 'application/json'
        }
      });
      
      const responseBody = JSON.parse(response.data.body);
      setImageUrls(responseBody.image_urls);
    } catch (error) {
      setError('Failed to fetch images');
      if (error.response) {
        setError((prevError) => prevError + `: ${error.response.data.error}`);
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="gallery-container">
      <h2 className="gallery-title">Generated Images</h2>
      <button onClick={fetchImages} className="fetch-button" disabled={loading}>
        {loading ? 'Fetching Images...' : 'Fetch Generated Images'}
      </button>
      {error && <div className="error-message">{error}</div>}
      {imageUrls.length > 0 ? (
        <div className="image-grid">
          {imageUrls.map((url) => (
            <div key={url} className="image-item">
              <img src={url} alt="Generated" className="gallery-image" />
            </div>
          ))}
        </div>
      ) : !loading && !error && (
        <div className="no-images">No images available</div>
      )}
    </div>
  );
};

export default ImageGallery;

// _frontend_vue/src/components/ImageGallery.vue
<template>
    <div>
      <h2>Generated Images</h2>
      <button @click="fetchImages">Fetch Generated Images</button>
      <div v-if="loading">Fetching images...</div>
      <div v-if="error">{{ error }}</div>
      <div v-if="imageUrls.length">
        <div class="image-container">
          <img v-for="url in imageUrls" :key="url" :src="url" :alt="url" />
        </div>
      </div>
    </div>
  </template>
  
  <script>
  import axios from 'axios';
  
  export default {
    data() {
      return {
        loading: false,
        error: null,
        imageUrls: [],
      };
    },
    methods: {
      async fetchImages() {
        this.loading = true;
        this.error = null;
        this.imageUrls = [];
  
        try {
          const response = await axios.get('https://00ewcs17p7.execute-api.us-east-1.amazonaws.com/dev-cors', {
            params: {
              bucket: 'ca-store-images',
              prefix: 'generated-images/'
            }
          });
          console.log("FETCHED IMAGES", response);
          const parsedResponseBody = JSON.parse(response.data.body);
          console.log('GENERATION RESPONSE IMAGE URL: ', parsedResponseBody.image_urls);
          this.imageUrls = parsedResponseBody.image_urls;
        } catch (error) {
          this.error = 'Failed to fetch images';
          if (error.response) {
            this.error += `: ${error.response.data.error}`;
          }
        } finally {
          this.loading = false;
        }
      },
    },
  };
  </script>
  
  <style scoped>
  button {
    padding: 10px 20px;
    margin-bottom: 20px;
  }
  .image-container {
    display: flex;
    flex-wrap: wrap;
  }
  img {
    max-width: 100%;
    margin: 10px;
  }
  </style>
